### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by trivigy** [paultag/aiodocker#9]
Cannot really install it through pypi.

**Comment by paultag** [comment]
It's basically abandoned -- I don't use much Docker anymore personally, but this is a dependency on some software I care about, so I'm maybe likely to get back to active development

Interested in being a co-maintainer?

**Comment by trivigy** [comment]
Definitely. I need some sort of this functionality for an active project within my company. I'll be happy to push it further and keep maintaining it. I just don't want to jump in if I won't have the ability or have someone with the ability to actually be able to keep pushing it upstream within pypi.

What's the best way to join in as a co-maintainer? I also eventually will likely pass it off to some younger engineer with within my company to maintain. (Just to keep that in mind)

**Comment by paultag** [comment]
@trivigy send some PRs, I promise to review them - after a good patch or two, I'll add y'all as a co-maintainer

**Comment by trivigy** [comment]
Alright. You got it.
